<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8"/>
 <title><?php echo $pageTitle; ?></title>
 <style>
 	body{background-color:#c5f1ff;
	 	width: 960px;
	 	margin-left:auto;
	 	margin-right:auto;
 	}
 	center{background-color:white;}
 	p{font-size: 24px;}
 	
 </style>
</head>

<center>
<p><b> Client List </b></p>
<p><a href="?action=">HOME</a> | <a href="?action=login">Login</a></p>
</center>

